config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  root to: 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/models/author.rb
	has_many :books
=======
has_many :books
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/models/author.rb
end

app/models/book.rb
class Book < ApplicationRecord
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/models/book.rb
	belongs_to :author
=======
belongs_to :author
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/models/book.rb
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :birth_year)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/controllers/books_controller.rb
      params.require(:book).permit(:Title, :Published_year,:author_id)
=======
      params.require(:book).permit(:title, :published_year,:author_id)
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/controllers/books_controller.rb
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birth_year %>
    <%= form.number_field :birth_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.birth_year %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @author.birth_year %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/_form.html.erb
    <%= form.label :Title %>
    <%= form.text_field :Title %>
=======
    <%= form.label :title %>
    <%= form.text_field :title %>
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/_form.html.erb
  </div>

  <div class="field">
    <%= form.label :published_year %>
    <%= form.number_field :published_year %>
  </div>
<div class="field">
    <%= form.label :author %>
    <%= collection_select(:book, :author_id, Author.all, :id,:name, prompt: true)%>
  </div>
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/_form.html.erb

  <div class="field">
    <%= form.label :Author %>
    <%= collection_select(:book, :author_id, Author.all, :id,:name, prompt: true)%>
  </div>

=======
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/_form.html.erb
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
<h1 >Books</h1>

<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/index.html.erb
<h1><center>Books</center></h1>

<table>
=======
<table border="4">
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/index.html.erb
  <thead>
    <tr>
      <th>Title</th>
      <th>Published year</th>
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/index.html.erb
       <th>Author</th>
=======
      <th>Author</th>
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/index.html.erb
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/index.html.erb
        <td><%= book.Title %></td>
        <td><%= book.Published_year %></td>
        <td><%= book.author.name %></td>
=======
        <td><%= book.title %></td>
        <td><%= book.published_year %></td>
         <td><%= book.author.name %></td>
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/index.html.erb
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/show.html.erb
  <%= @book.Title %>
=======
  <%= @book.title %>
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/show.html.erb
</p>

<p>
  <strong>Published year:</strong>
  <%= @book.published_year %>
</p>
<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>
<<<<<<< HEAD:Rakhi/Assignment2-foreignkey/app/views/books/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>

=======
>>>>>>> e119317a0f623e0eae36b8312c36026beb434c37:Nirmala/assignment2/app/views/books/show.html.erb
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>As2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>